version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: onion_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./nginx/sshd_config:/etc/ssh/sshd_config
    networks:
      - onion_net

  tor:
    image: dperson/torproxy:latest
    container_name: onion_tor
    volumes:
      - ./tor/torrc:/etc/tor/torrc
      - ./tor/hidden_service:/var/lib/tor/hidden_service
    networks:
      - onion_net

networks:
  onion_net:
    driver: bridge